version: 2

build:
  tools:
    python: '3.10'
  jobs:
    post_build:
      - pip list

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true

conda:
  environment: docs/environment.yml

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
