version: 2

build:
  os: ubuntu-22.04

sphinx:
   configuration: docs/source/conf.py
   fail_on_warning: true

conda:
  environment: docs/environment.yml

python:
   install:
    - method: pip
      path: .
      extra_requirements:
          - docs
